version: '2'
# Please note that docker-compose does not prescribe a startup order

services:
    #odsupercomponent
    odsupercomponent:
        build: .
        image: seresearch/opendavinci-ubuntu-16.04-complete:latest
        network_mode: "host"
        volumes:
        - .:/opt/recordings
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1  --configuration=/opt/recordings/configuration"
        
    #proxy-velodyne
    velodyne:
        build: .
        image: seresearch/opendavinci-ubuntu-16.04-complete:latest
        network_mode: "host"
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        ipc: host
        user: root
        restart: always
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"
        

        

